name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      run: |
        mkdir -p public
        echo "# Allow all web crawlers\nUser-agent: *\nAllow: /\n\n# Sitemap location\nSitemap: https://mcpsx.run/sitemap.xml" > public/robots.txt
        npm run deploy
